# Use root/example as user/password credentials
# You may need to change the client uri to a format like ~> mongodb://user:pass@host:port/
# Mongo Express provides a simple lightweight web administrative interface for mongoDB
version: '3'
services:
  medallion:
    build:
      context: .
      dockerfile: docker_utils/Dockerfile
    command: [sh, -c, "medallion --host 0.0.0.0"]
    environment:
      MEDALLION_BACKEND_MODULE_CLASS: "MemoryBackend"
    ports:
      - "5000:5000"
